//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace preproject2MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class linebotDBEntities : DbContext
    {
        public linebotDBEntities()
            : base("name=linebotDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrator { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<order_list> order_list { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<products_in_order> products_in_order { get; set; }
        public virtual DbSet<status_history> status_history { get; set; }
    }
}
